//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Domain.Impl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Textos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Core.Domain.Impl.Textos", typeof(Textos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyValue} não é um E-mail válido..
        /// </summary>
        public static string Geral_Mensagem_Email_Invalido {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Email_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} não pode ser vazio..
        /// </summary>
        public static string Geral_Mensagem_Erro_Campo_null {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Erro_Campo_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} não é um data válida.
        /// </summary>
        public static string Geral_Mensagem_Erro_DataInvalida {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Erro_DataInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} não contém um valor válida.
        /// </summary>
        public static string Geral_Mensagem_Erro_DecimalInvalido {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Erro_DecimalInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um registro com o nome informado..
        /// </summary>
        public static string Geral_Mensagem_Erro_NomeDuplicado {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Erro_NomeDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} não é um número válida.
        /// </summary>
        public static string Geral_Mensagem_Erro_NumeroInvalido {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Erro_NumeroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do campo {PropertyName} está fora do permitido..
        /// </summary>
        public static string Geral_Mensagem_Erro_Tamanho_Campo {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Erro_Tamanho_Campo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login e/ou senha informados são inválidos.
        /// </summary>
        public static string Geral_Mensagem_Login_Invalido {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Login_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação concluída com sucesso..
        /// </summary>
        public static string Geral_Mensagem_Sucesso {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro atualizado com sucesso..
        /// </summary>
        public static string Geral_Mensagem_Sucesso_Alteracao {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Sucesso_Alteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro removido com sucesso..
        /// </summary>
        public static string Geral_Mensagem_Sucesso_Exclusao {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Sucesso_Exclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro incluído com sucesso..
        /// </summary>
        public static string Geral_Mensagem_Sucesso_Inclusao {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Sucesso_Inclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status alterado com sucesso!.
        /// </summary>
        public static string Geral_Mensagem_Sucesso_Troca_Status {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Sucesso_Troca_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário desativado, entre em contato com o administrador.
        /// </summary>
        public static string Geral_Mensagem_Usuario_Desativado {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Usuario_Desativado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário não possui perfil definido, entre em contato com o administrador.
        /// </summary>
        public static string Geral_Mensagem_Usuario_Sem_Perfil {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Usuario_Sem_Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na validação. Campo Booleano Inválido..
        /// </summary>
        public static string Shared_Mensagem_Erro_String_To_Boolean {
            get {
                return ResourceManager.GetString("Shared_Mensagem_Erro_String_To_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na validação. Campo Data Inválida..
        /// </summary>
        public static string Shared_Mensagem_Erro_String_To_DateTime {
            get {
                return ResourceManager.GetString("Shared_Mensagem_Erro_String_To_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na validação. Campo Decimal Inválido..
        /// </summary>
        public static string Shared_Mensagem_Erro_String_To_Decimal {
            get {
                return ResourceManager.GetString("Shared_Mensagem_Erro_String_To_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na validação. Campo Double Inválido..
        /// </summary>
        public static string Shared_Mensagem_Erro_String_To_Double {
            get {
                return ResourceManager.GetString("Shared_Mensagem_Erro_String_To_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na validação. Campo inteiro Inválido. .
        /// </summary>
        public static string Shared_Mensagem_Erro_String_To_Int {
            get {
                return ResourceManager.GetString("Shared_Mensagem_Erro_String_To_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na validação. Campo Inteiro de 64Bits Inválido..
        /// </summary>
        public static string Shared_Mensagem_Erro_String_To_Int64 {
            get {
                return ResourceManager.GetString("Shared_Mensagem_Erro_String_To_Int64", resourceCulture);
            }
        }
    }
}
